import '../models/bond_model.dart';

class BondsRepository {
  static List<BondModel> getBondsMarket() {
    return getIndianBondsMarket();
  }

  static List<BondModel> getIndianBondsMarket() {
    return [
      // Sovereign & G-Secs
      BondModel(
        isin: 'IN0020230085',
        name: '7.18% Government of India GS 2033',
        issuer: 'Government of India (Central G-Sec)',
        category: BondCategory.gSec,
        cleanPrice: 100.12,
        faceValue: 100.0,
        couponRate: 7.18,
        ytmPercent: 7.12,
        creditRating: 'SOV (AAA equivalent)',
        frequency: CouponFrequency.semiAnnual,
        maturityDate: DateTime(2033, 8, 14),
        keyAdvantage:
            'Zero credit default risk with benchmark market liquidity.',
        officialChannel: 'RBI Retail Direct',
      ),
      BondModel(
        isin: 'IN3320230142',
        name: '7.42% Tamil Nadu SDL 2034',
        issuer: 'Government of Tamil Nadu',
        category: BondCategory.stateSdl,
        cleanPrice: 99.85,
        faceValue: 100.0,
        couponRate: 7.42,
        ytmPercent: 7.46,
        creditRating: 'SOV (State)',
        frequency: CouponFrequency.semiAnnual,
        maturityDate: DateTime(2034, 1, 24),
        keyAdvantage:
            'Sovereign spread premium (+25-30 bps over Central G-Secs).',
        officialChannel: 'RBI Retail Direct',
      ),
      BondModel(
        isin: 'IN002023X364',
        name: '364-Day Treasury Bill',
        issuer: 'Reserve Bank of India',
        category: BondCategory.tBill,
        cleanPrice: 93.65,
        faceValue: 100.0,
        couponRate: 0.0,
        ytmPercent: 6.78,
        creditRating: 'SOV',
        frequency: CouponFrequency.cumulativeAtMaturity,
        maturityDate: DateTime(2027, 5, 15),
        keyAdvantage:
            'Short-term zero coupon cash parking backed by sovereign credit.',
        officialChannel: 'RBI Retail Direct',
      ),

      // PSU Bonds (AAA Rated)
      BondModel(
        isin: 'INE020B08DF6',
        name: 'REC Limited Taxable Bonds 2029 (AAA)',
        issuer: 'Rural Electrification Corporation (REC)',
        category: BondCategory.psuSecuredAaa,
        cleanPrice: 100.20,
        faceValue: 10000.0,
        couponRate: 7.55,
        ytmPercent: 7.65,
        creditRating: 'CRISIL AAA',
        frequency: CouponFrequency.annual,
        maturityDate: DateTime(2029, 6, 30),
        keyAdvantage: 'Maharatna PSU backing with top-tier AAA credit rating.',
        officialChannel: 'NSE / BSE Debt Segment',
      ),
      BondModel(
        isin: 'INE261F08DV1',
        name: 'NABARD AAA Corporate Bond 2028',
        issuer: 'National Bank for Agriculture and Rural Development',
        category: BondCategory.psuSecuredAaa,
        cleanPrice: 100.10,
        faceValue: 10000.0,
        couponRate: 7.50,
        ytmPercent: 7.60,
        creditRating: 'CRISIL AAA',
        frequency: CouponFrequency.annual,
        maturityDate: DateTime(2028, 12, 15),
        keyAdvantage: 'Quasi-sovereign financial institution safety.',
        officialChannel: 'NSE / BSE Debt Segment',
      ),
      BondModel(
        isin: 'INE134E08LP9',
        name: 'Power Finance Corp (PFC) Bond 2031',
        issuer: 'Power Finance Corporation',
        category: BondCategory.psuSecuredAaa,
        cleanPrice: 99.80,
        faceValue: 10000.0,
        couponRate: 7.60,
        ytmPercent: 7.70,
        creditRating: 'CRISIL AAA',
        frequency: CouponFrequency.semiAnnual,
        maturityDate: DateTime(2031, 3, 31),
        keyAdvantage: 'Semi-annual cashflow with strong institutional demand.',
        officialChannel: 'NSE / BSE Debt Segment',
      ),

      // Top Corporate Bonds (AAA & AA+)
      BondModel(
        isin: 'INE002A08534',
        name: 'Reliance Industries Ltd Secured NCD',
        issuer: 'Reliance Industries Limited',
        category: BondCategory.privateCorporateAaa,
        cleanPrice: 100.30,
        faceValue: 100000.0,
        couponRate: 7.75,
        ytmPercent: 7.85,
        creditRating: 'CRISIL AAA',
        frequency: CouponFrequency.annual,
        maturityDate: DateTime(2027, 11, 10),
        keyAdvantage: 'Bluechip balance sheet strength with CRISIL AAA rating.',
        officialChannel: 'NSE / BSE Debt Segment',
      ),
      BondModel(
        isin: 'INE040A08377',
        name: 'HDFC Bank Tier-2 Subordinated Bond',
        issuer: 'HDFC Bank Limited',
        category: BondCategory.privateCorporateAaa,
        cleanPrice: 100.50,
        faceValue: 100000.0,
        couponRate: 7.80,
        ytmPercent: 7.90,
        creditRating: 'CRISIL AAA',
        frequency: CouponFrequency.annual,
        maturityDate: DateTime(2034, 8, 25),
        keyAdvantage: 'India’s premier private banking debt security.',
        officialChannel: 'NSE Debt Segment',
      ),
      BondModel(
        isin: 'INE306N07LG1',
        name: 'Tata Capital Financial Services NCD',
        issuer: 'Tata Capital Financial Services',
        category: BondCategory.privateCorporateAaa,
        cleanPrice: 99.70,
        faceValue: 1000.0,
        couponRate: 8.10,
        ytmPercent: 8.25,
        creditRating: 'CRISIL AA+',
        frequency: CouponFrequency.annual,
        maturityDate: DateTime(2028, 1, 14),
        keyAdvantage: 'High retail yield backed by the Tata parentage.',
        officialChannel: 'NSE / BSE Retail Book',
      ),
      BondModel(
        isin: 'INE498L07BC8',
        name: 'L&T Finance Holdings Secured NCD',
        issuer: 'L&T Finance Holdings',
        category: BondCategory.privateCorporateAaa,
        cleanPrice: 99.50,
        faceValue: 1000.0,
        couponRate: 8.25,
        ytmPercent: 8.40,
        creditRating: 'CRISIL AA+',
        frequency: CouponFrequency.annual,
        maturityDate: DateTime(2029, 9, 19),
        keyAdvantage: 'Secured asset-backed structure with AA+ rating.',
        officialChannel: 'NSE / BSE Retail Book',
      ),

      // Mid-Tier Corporate Bonds (AA & A)
      BondModel(
        isin: 'INE414G07HS9',
        name: 'Muthoot Finance Secured Redeemable NCD',
        issuer: 'Muthoot Finance Limited',
        category: BondCategory.highYieldNcd,
        cleanPrice: 99.40,
        faceValue: 1000.0,
        couponRate: 8.90,
        ytmPercent: 9.10,
        creditRating: 'CRISIL AA',
        frequency: CouponFrequency.annual,
        maturityDate: DateTime(2028, 4, 23),
        keyAdvantage:
            'Higher coupon backed by liquid gold collateral reserves.',
        officialChannel: 'NSE / BSE Retail Book',
      ),
      BondModel(
        isin: 'INE530L07210',
        name: 'Edelweiss Financial Services NCD',
        issuer: 'Edelweiss Financial Services',
        category: BondCategory.highYieldNcd,
        cleanPrice: 98.90,
        faceValue: 1000.0,
        couponRate: 10.20,
        ytmPercent: 10.50,
        creditRating: 'CRISIL A',
        frequency: CouponFrequency.annual,
        maturityDate: DateTime(2028, 7, 15),
        keyAdvantage:
            'Double-digit yield for yield-seeking aggressive portfolios.',
        officialChannel: 'NSE / BSE Retail Book',
      ),

      // High Yield / Retail Corporate Bonds (BBB-)
      BondModel(
        isin: 'INE619I07111',
        name: 'A2Z Infrastructure Series Bond',
        issuer: 'A2Z Infrastructure Limited',
        category: BondCategory.highYieldNcd,
        cleanPrice: 98.00,
        faceValue: 1000.0,
        couponRate: 11.75,
        ytmPercent: 12.20,
        creditRating: 'CARE BBB-',
        frequency: CouponFrequency.annual,
        maturityDate: DateTime(2027, 11, 30),
        keyAdvantage:
            'High risk-adjusted yield for speculative credit allocations.',
        officialChannel: 'NSE / BSE Retail Book',
      ),
    ];
  }
}
